import 'reflect-metadata';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import request from 'supertest';
import { randomUUID } from 'node:crypto';
import { removeSection, sectionIssues } from '../../src/modules/exams/section-structure';
import { createExamSchema } from '../../src/modules/exams/exam.types';

async function main() {
  const target = new URL(process.env.DATABASE_URL!);
  assert(['localhost', '127.0.0.1'].includes(target.hostname) && target.pathname.endsWith('_test'));
  const sections = [{ key: 'a', title: 'First', position: 0, pinned: true }, { key: 'b', title: 'Second', position: 1 }, { key: 'c', title: 'Third', position: 2 }];
  const questions = Array.from({length: 10}, (_, i) => ({id: randomUUID(), sectionKey: i === 0 ? null : i < 9 ? 'b' : 'a', type: 'short_text' as const, prompt: `Question ${i + 1}`, correctAnswers: ['yes'], explanation: 'Keep explanation', graded: false, points: 3, required: true, pinned: i === 2, maxTimeSeconds: 30, position: i}));
  const moved = removeSection(sections, questions, 'b', 'a');
  assert.equal(moved.questions.length, 10); assert.equal(moved.sections.length, 2);
  assert.deepEqual(moved.questions.map(q => q.id), [questions[0].id, questions[9].id, ...questions.slice(1,9).map(q => q.id)]);
  moved.questions.forEach(q => { const original = questions.find(o => o.id === q.id)!; const {sectionId, sectionKey, position, ...content} = q; const {sectionKey: _s, position: _p, ...expected} = original; assert.deepEqual(content, expected); });
  assert.equal(moved.sections[0].pinned, true);
  assert.equal(removeSection([sections[1]], questions.slice(1,9), 'b', '').sections.length, 0);
  assert(removeSection([sections[1]], questions.slice(1,9), 'b', '').questions.every(q => q.sectionId === null && q.sectionKey === null));
  assert.throws(() => removeSection(sections, questions, 'b', 'missing'));
  assert.throws(() => removeSection(sections, questions, 'b', 'b'));
  assert(sectionIssues({sections: [sections[0], sections[0]]}).length);
  assert(!createExamSchema.safeParse({title:'Invalid', sections, questions:[{...questions[0], sectionKey:'missing'}]}).success);
  console.log('PASS safe moves, exact question preservation, append ordering, pins, zero sections, invalid destinations/references');
  const f = JSON.parse(fs.readFileSync('.smoke/browser-fixture.json', 'utf8'));
  const { createApp } = await import('../../src/api/server');
  const app = createApp(); const auth = {Authorization: `Bearer ${f.token}`}; const base = `/api/orgs/${f.orgId}/exams`;
  const input = {title: 'Section management smoke', status:'published', preventFocusLoss:false, maxAttempts:20, sections, questions};
  const created = await request(app).post(base).set(auth).send(input); assert.equal(created.status,201,JSON.stringify(created.body));
  const exam = created.body.data; const definition = {...input, ...moved};
  const saved = await request(app).put(`${base}/${exam.id}/definition`).set(auth).send(definition); assert.equal(saved.status,200,JSON.stringify(saved.body));
  const reloaded = (await request(app).get(`${base}/${exam.id}`).set(auth)).body.data;
  assert.equal(reloaded.questions.length,10); assert.equal(reloaded.sections.length,2);
  assert.deepEqual(reloaded.questions.map((q: any) => q.id), moved.questions.map(q => q.id));
  const invalid = await request(app).put(`${base}/${exam.id}/definition`).set(auth).send({...definition,questions:[{...questions[0],sectionId:randomUUID()}]}); assert.equal(invalid.status,400);
  console.log('PASS API save/reload preserves all questions and rejects foreign references');
  const attempt = await request(app).post(`/api/public/exams/${exam.publicId}/start`).send({respondentName:'Local smoke',deviceId:randomUUID()});
  assert.equal(attempt.status,201,JSON.stringify(attempt.body));
  assert.deepEqual(attempt.body.data.attempt.questions.map((q:any)=>q.id),moved.questions.map(q=>q.id));
  const locked = await request(app).put(`${base}/${exam.id}/definition`).set(auth).send(definition); assert.equal(locked.status,409);
  const { ExamRepository } = await import('../../src/modules/exams/exam.repository');
  const repository = new ExamRepository();
  await assert.rejects(repository.replaceDefinition(f.orgId, exam.id, definition as any), (error: any) => error.code === 'EXAM_STRUCTURE_LOCKED');
  await assert.rejects(repository.createAttempt({ examId: exam.id, expectedUpdatedAt: new Date(0) } as any), (error: any) => error.code === 'EXAM_CHANGED');
  console.log('PASS transaction-level attempt lock and stale attempt snapshot rejection');
  console.log('PASS actual attempt contains every question once in group order; subsequent structural save locked');
  const editable = await request(app).post(base).set(auth).send({...input,title:'Section UI smoke',questions:questions.map(q=>({...q,id:randomUUID()}))}); assert.equal(editable.status,201);
  fs.writeFileSync('.smoke/sections-fixture.json',JSON.stringify({orgId:f.orgId,examId:editable.body.data.id,publicId:editable.body.data.publicId},null,2));
}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
