ALTER TABLE "orgs"
ADD COLUMN IF NOT EXISTS "plan" VARCHAR(50) NOT NULL DEFAULT 'free';

ALTER TABLE "orgs"
ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(50) NULL;

ALTER TABLE "orgs"
ADD COLUMN IF NOT EXISTS "subscription_id" VARCHAR(255) NULL;

ALTER TABLE "orgs"
ADD COLUMN IF NOT EXISTS "current_period_end" TIMESTAMP NULL;